server.port=8080
spring.session.timeout=900
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50

# MongoDB connection string
spring.data.mongodb.database=billingapp_db
spring.data.mongodb.uri=mongodb://user:qwerty@localhost:27017/billingapp_db

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.use-root-path=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-login-endpoint=true
springdoc.packagesToScan=com.paymentchain.billing.entities, com.paymentchain.billing.controller
springdoc.pathsToMatch=/v1, /billing/**

spring.security.user.name=${APP_USER:admin}
spring.security.user.password=${APP_USER:admin}
spring.security.user.roles=ADMIN